// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Only MySQL and JavaScript are shown for now; other doc folders still
  // exist and remain reachable by direct URL, just not listed here.
  tutorialSidebar: [
    {type: 'autogenerated', dirName: 'MySQL'},
    {type: 'autogenerated', dirName: 'JavaScript'},
  ],
};

export default sidebars;
