// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Only Claude, MySQL and JavaScript are shown for now; other doc folders still
  // exist and remain reachable by direct URL, just not listed here.
  // Each is wrapped in its own category so the sidebar shows collapsed
  // folders first, and only expands to individual articles on click.
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Claude',
      items: [{type: 'autogenerated', dirName: 'claude'}],
    },
    {
      type: 'category',
      label: 'MySQL',
      items: [{type: 'autogenerated', dirName: 'MySQL'}],
    },
    {
      type: 'category',
      label: 'JavaScript',
      items: [{type: 'autogenerated', dirName: 'JavaScript'}],
    },
  ],
};

export default sidebars;
